- name: Install docker
  tags:
    - docker
  become: yes
  become_user: root
  block:
    - name: Check if docker is already installed
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker_installed
    - name: Docker already installed macos
      ansible.builtin.stat:
        path: /usr/local/bin/docker
      register: docker_installed_macos
    - name: install with convenience script
      when: docker_installed.stat.exists == False and docker_installed_macos.stat.exists == False
      shell: >
        curl -fsSL https://get.docker.com | sh
    - name: Add docker compose alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "alias docker-compose='docker compose'"

- name: Install docker arch
  tags:
    - arch
  become: yes
  become_user: root
  block:
    - name: Install docker with pacman
      pacman:
        name: docker
        state: present
    - name: Install docker compose
      pacman:
        name: docker-compose
        state: present
  when: ansible_distribution == "Arch Linux"
