- name: Install fzf ubuntu
  become: yes
  become_user: root
  apt:
    name: fzf
    state: present
  when: ansible_os_family == "Debian"

- name: Install fzf arch
  become: yes
  become_user: root
  tags:
    - arch
  pacman:
    name: fzf
    state: present
  when: ansible_distribution  == "Archlinux"

- name: Install fzf macos
  ansible.builtin.homebrew:
    name: fzf
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
