- name: Install golang linux
  block:
    - name: Get latest Go version
      shell: |
        echo 1.22.0
      register: go_version
    - name: Install Go 1.22.0 Linux
      become: yes
      become_user: root
      block:
        - name: Cleanup golang folder
          shell: 'rm -rf /usr/local/go'
        - name: Download and unarchive golang
          ansible.builtin.unarchive:
            src: https://go.dev/dl/go{{ go_version.stdout }}.linux-amd64.tar.gz
            dest: /usr/local
            remote_src: yes
  when: ansible_os_family == "Debian"

- name: Install golang macos

  block:
    - name: Get latest Go version
      shell: |
        echo 1.22.0
      register: go_version
    - name: Clear existing install
      become: yes
      become_user: root
      shell: |
        rm -rf /usr/local/go
    - name: Install Go Macos
      become: yes
      become_user: root
      shell: |
        curl -s https://dl.google.com/go/go{{ go_version.stdout }}.darwin-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: add golang to path
      ansible.builtin.shell: >
        echo 'export GOPATH=$HOME/go' >> ~/.zshrc
        echo 'export PATH=$GOPATH/bin:$PATH' >> ~/.zshrc
  when: ansible_os_family == "Darwin"
