---
- name: Local setup
  hosts: localhost

  vars:
    source_key: "./files/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    go_version: "1.20"

  tasks:
    - include_tasks: ssh.yaml
      tags:
        - ssh
        - terminal
    - include_tasks: stow.yaml
      tags:
        - stow
    - include_tasks: tmux.yaml
      tags:
        - tmux
        - terminal
    - include_tasks: fonts.yaml
      tags:
        - fonts
        - terminal
    - include_tasks: terminal.yaml
      tags:
        - terminal
