---
- name: Local setup
  hosts: localhost

  vars:
    source_key: "./files/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    go_version: "1.22"

    neovim_name: neovim
    neovim_ppa: ppa:neovim-ppa/unstable
    install_state: present
    python_required_packages:
      - software-properties-common
    ycm_packages:
      - build-essential
      - cmake
  tasks:
    - include_tasks: terminal.yaml
      tags:
        - terminal
    - include_tasks: brew.yaml
      tags:
        - brew
    - include_tasks: ssh.yaml
      tags:
        - ssh
        - terminal
    - include_tasks: git.yaml
      tags:
        - git
    - include_tasks: stow.yaml
      tags:
        - stow
    - include_tasks: tmux.yaml
      tags:
        - tmux
        - terminal
    - include_tasks: gdebi.yaml
      tags:
        - gdebi
    - include_tasks: fonts.yaml
      tags:
        - fonts
        - terminal
    - include_tasks: node.yaml
      tags:
        - nvm
        - node
    - include_tasks: python.yaml
      tags:
        - pyenv
        - python

    - include_tasks: rust.yaml
      tags:
        - rust
    - include_tasks: golang.yaml
      tags:
        - go
    - include_tasks: neovim.yaml
      tags:
        - nvim
    # Tooling
    - include_tasks: fzf.yaml
      tags:
        - fzf
        - tooling
    - include_tasks: ripgrep.yaml
      tags:
        - tooling
        - ripgrep
    - include_tasks: docker.yaml
      tags:
        - docker
    - include_tasks: zoxide.yaml
      tags:
        - zoxide
    - include_tasks: 1password.yaml
      tags:
        - 1password
    - include_tasks: nix.yaml
      tags:
        - nix
    - include_tasks: mongoshell.yaml
      tags:
        - mongo
