---
- name: Local setup
  hosts: localhost

  vars:
    source_key: "./files/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    go_version: "1.22"

    neovim_name: neovim
    neovim_ppa: ppa:neovim-ppa/unstable
    install_state: present
    python_required_packages:
      - software-properties-common
    ycm_packages:
      - build-essential
      - cmake

  tasks:
    - include_tasks: terminal.yaml
      tags:
        - terminal
        - arch

    - include_tasks: brew.yaml
      tags:
        - brew

    - include_tasks: ssh.yaml
      tags:
        - ssh
        - terminal
        - arch
    - include_tasks: git.yaml
      tags:
        - git
    - include_tasks: stow.yaml
      tags:
        - stow
        - arch
    - include_tasks: tmux.yaml
      tags:
        - tmux
        - terminal
        - arch

    - include_tasks: gdebi.yaml
      tags:
        - gdebi
        - arch

    - include_tasks: fonts.yaml
      tags:
        - fonts
        - terminal
        - arch

    - include_tasks: node.yaml
      tags:
        - nvm
        - node
        - arch

    - include_tasks: python.yaml
      tags:
        - pyenv
        - python
        - arch

    - include_tasks: rust.yaml
      tags:
        - rust
        - arch
    - include_tasks: golang.yaml
      tags:
        - golang
        - arch

    - include_tasks: neovim.yaml
      tags:
        - nvim
        - arch

    # Tooling
    - include_tasks: fzf.yaml
      tags:
        - tooling
        - arch
    - include_tasks: ripgrep.yaml
      tags:
        - tooling
        - arch

    - include_tasks: docker.yaml
      tags:
        - docker
        - arch

    - include_tasks: zoxide.yaml
      tags:
        - zoxide
        - arch

    - include_tasks: nix.yaml
      tags:
        - nix
        - arch
