- name: Install mongodb utilities ubuntu
  become: yes
  become_user: root
  tags:
    - mongo
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Mongosh installation
      block:
        - name: Download mongosh
          get_url:
            url: https://downloads.mongodb.com/compass/mongodb-mongosh_2.2.1_amd64.deb
            dest: /tmp/mongosh.deb
        - name: Install mongosh
          apt:
            deb: /tmp/mongosh.deb
            state: present

    - name: Mongodb tools installation
      block:
        - name: Create temp folder for mongodb tools
          file:
            path: /tmp/mongodb-database-tools
            state: directory
        - name: Download mongodb tools
          get_url:
            url: https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.4.deb
            dest: /tmp/mongodb-database-tools/installer.deb
        - name: Install mongodb tools
          apt:
            deb: /tmp/mongodb-database-tools/installer.deb
            state: present

- name: Install mongodb utilities macos
  when: ansible_os_family == "Darwin"
  tags:
    - mongo
  block:
    - name: Install mongosh
      ansible.builtin.homebrew:
        name: mongosh
        state: present
    - name: Tab brew formula for mongodb tools
      shell: brew tap mongodb/brew
    - name: Install mongodb tools
      ansible.builtin.homebrew:
        name: mongodb-database-tools
        state: present
