- name: Install ripgrep
  apt:
    name: ripgrep
    state: present
  when: ansible_os_family == "Debian"

- name: Install ripgrep macos
  ansible.builtin.homebrew:
    name: ripgrep
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"

- name: Install ripgrep arch linux
  become: yes
  become_user: root
  tags:
    - arch
  pacman:
    name: ripgrep
    state: present
