- name: Install stow Linux
  become: yes
  become_user: root
  block:
    - name: Install Stow
      ansible.builtin.apt:
        name: stow
        state: present
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - stow

- name: Install stow Macos
  ansible.builtin.homebrew:
    name: stow
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
  tags:
    - stow

- name: Install stow Arch linux
  become: yes
  become_user: root
  block:
    - name: Install Stow
      pacman:
        name: stow
        state: present
  when: ansible_architecture == "x86_64"
  tags:
    - stow
    - arch


