- name: Install Fish
  block:
    - name: Install fish
      ansible.builtin.apt:
        name: zsh
        state: present
      when: ansible_os_family == "Debian"

- name: Change shell to zsh
  become: yes
  become_user: root
  shell: chsh -s `which zsh`

- name: Cleanup ohmyzsh
  ansible.builtin.shell: >
    rm -rf ~/.oh-my-zsh

- name: install Oh My Zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install ohmyzsh autosuggestions
  ansible.builtin.git:
    dest: "~/.zsh/zsh-autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
- name: Source zsh autosuggestions
  lineinfile:
    path: ~/.zshrc
    line: "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"

- name: Add autosuggestions plugin to zsh
  lineinfile:
    path: ~/.zshrc
    line: "plugins=(git zsh-autosuggestions)"
