- name: Setup TMUX
  tags:
    - tmux
    - terminal
  block:
    - name: Install tmux
      ansible.builtin.homebrew:
        name: tmux
        state: present

- name: Setup TMUX config
  tags:
    - tmux
    - terminal
  block:
    - name: Install tmux package manager
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
- name: Copy TMUX dotfiles
  ansible.builtin.shell: >
    stow -t ~/ -d dotfiles tmux
