#!/usr/bin/env bash

languages=`echo "c cpp typescript rust python nodejs golang" | tr ' ' '\n' | sort | uniq`
core_utils=`echo "find xargs sed awk" | tr ' ' '\n' | sort | uniq`

selected=`echo -e "$languages\n$core_utils" | fzf`

read -p "Enter your query: " query

if echo "$languages" | grep -qs $selected; then
  # curl "cht.sh/$selected/$(echo $query | tr ' ' '+')" | less
  tmux new-window -n "cht.sh" "curl \"cht.sh/$selected/$(echo $query | tr ' ' '+')\" | less"
else
  # curl "cht.sh/$selected~$query" | less
  tmux new-window -n "cht.sh" "curl \"cht.sh/$selected~$query\" | less"
fi
